global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'root@localhost.localdomain'
    from: 'root@localhost.localdomain'
    smarthost: 127.0.0.1:25
    require_tls: false
