{
 "title": "TungstenFabric",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Controller Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "num_of_config_nodes", "legendFormat": "num_of_controller_nodes" },
    { "expr": "num_of_analytics_nodes", "legendFormat": "num_of_analytics_nodes" },
    { "expr": "num_of_config_database_nodes", "legendFormat": "num_of_config_database_nodes" }
   ]
  },
  {
   "title": "Number of Alarms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(ALERTS) OR vector(0)", "legendFormat": "Total" },
    {
     "expr": "max without (job, severity, alertstate, instance) (ALERTS)"
    }
   ]
  },
  {
   "title": "cpu_share",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (host_id) (cpu_share))"
    }
   ]
  },
  {
   "title": "mem_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (host_id) (mem_used / mem_total * 100))"
    }
   ]
  },
  {
   "title": "disk_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (host_id) (disk_usage{mountpoint=\"_dev_mapper_centos_root\"}))"
    }
   ]
  },
  {
   "title": "load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, max by (host_id) (one_min_avg))"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of devices",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "sum(num_of_fabrics)", "legendFormat": "num_of_fabrics" },
      { "expr": "sum(num_of_physical_routers)", "legendFormat": "num_of_physical_routers" },
      {
       "expr": "sum(num_of_virtual_port_groups)",
       "legendFormat": "num_of_virtual_port_groups"
      },
      {
       "expr": "sum(num_of_physical_interfaces)",
       "legendFormat": "num_of_physical_interfaces"
      }
     ]
    },
    {
     "title": "Number of device commits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (host_id) (total_commits_sent_since_up)"
      }
     ]
    }
   ]
  },
  { "title": "Control / vRouter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Number of objects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "num_of_vrouters", "legendFormat": "num_of_vrouters" },
    { "expr": "num_of_virtual_networks", "legendFormat": "num_of_virtual_networks" },
    { "expr": "num_of_virtual_machines", "legendFormat": "num_of_virtual_machines" },
    {
     "expr": "num_of_virtual_machine_interfaces",
     "legendFormat": "num_of_virtual_machine_interfaces"
    }
   ]
  },
  {
   "title": "control bgp / xmpp peer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "num_up_bgp_peer / num_bgp_peer * 100",
     "legendFormat": "up bgp peer"
    },
    {
     "expr": "num_up_xmpp_peer/ num_xmpp_peer * 100",
     "legendFormat": "up xmpp peer"
    }
   ]
  },
  {
   "title": "vrouter bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(5, phy_if_stats_in_bytes)" },
    {
     "expr": "topk(5, phy_if_stats_out_bytes)"
    }
   ]
  },
  {
   "title": "vRouter flow",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flow_rate_active_flows" },
    {
     "expr": "flow_rate_max_flow_adds_per_second"
    }
   ]
  }
 ]
}